detector: ml
model_type: firemlp
checkpoint: checkpoint/fire_detector_mlp_best.pt
threshold: 0.5
T_ignition: 300    # [°C]
training:
  loss: error-rate
  layers:
  - 64
  - 32
  learning_rate: 0.01
  epochs: 100
  importance_weights:
    gt: 10
    fire: 5
    other: 1
metrics:
  error_rate: 0.06671812968681076
  precision: 0.9726348709929633
  recall: 0.9602999558888399
  TP: 8708
  FP: 245
  FN: 360
  TN: 519534
